import nodemailer from 'nodemailer';

function isPlaceholderPassword(pwd?: string): boolean {
  if (!pwd) return true;
  const trimmed = pwd.trim();
  return (
    trimmed.length === 0 ||
    trimmed.includes('••••') ||
    trimmed.startsWith('<') ||
    trimmed === 'apikey' ||
    trimmed === 'password'
  );
}

function resolveSmtpCredentials(smtpConfig?: any) {
  const envHost = process.env.SMTP_HOST;
  const envUser = process.env.SMTP_USER || process.env.SMTP_USERNAME;
  const envPass = process.env.SMTP_PASS || process.env.SMTP_PASSWORD;
  const envPort = process.env.SMTP_PORT;
  const envFrom = process.env.SMTP_FROM;
  const envSecure = process.env.SMTP_SECURE === 'true';

  let host = smtpConfig?.host;
  let username = smtpConfig?.username;
  let password = smtpConfig?.password;
  let port = Number(smtpConfig?.port);
  let secure = Boolean(smtpConfig?.secure);
  let fromEmail = smtpConfig?.fromEmail;
  let fromName = smtpConfig?.fromName;
  let replyTo = smtpConfig?.replyToEmail;

  if (isPlaceholderPassword(password) && envPass) {
    password = envPass;
  }

  if ((!host || host === 'smtp.sendgrid.net') && envHost) {
    host = envHost;
  }

  if ((!username || username === 'apikey') && envUser) {
    username = envUser;
  }

  if (!port && envPort) {
    port = Number(envPort);
  }

  if (!port) {
    port = secure || port === 465 ? 465 : 587;
  }

  if (!fromEmail && envFrom) {
    fromEmail = envFrom;
  }

  if (!fromEmail && username && username.includes('@')) {
    fromEmail = username;
  }

  if (!fromEmail) {
    fromEmail = 'events@columbiamarket.org';
  }

  if (!fromName) {
    fromName = 'Columbia Community Festival';
  }

  const hasRealCredentials = Boolean(
    host &&
    username &&
    password &&
    !isPlaceholderPassword(password)
  );

  return {
    host: host || 'smtp.sendgrid.net',
    username: username || 'apikey',
    password: password || '',
    port,
    secure: secure || port === 465 || envSecure,
    fromEmail,
    fromName,
    replyTo: replyTo || fromEmail,
    hasRealCredentials
  };
}

export default async function handler(req: any, res: any) {
  res.setHeader('Content-Type', 'application/json');

  if (req.method !== 'POST') {
    return res.status(405).json({ success: false, error: 'Method Not Allowed' });
  }

  let body = req.body;
  if (typeof body === 'string') {
    try {
      body = JSON.parse(body);
    } catch {}
  }

  const { host: reqHost, port: reqPort, secure: reqSecure, username: reqUser, password: reqPass, fromEmail: reqFrom, fromName: reqFromName, recipientEmail } = body || {};

  const creds = resolveSmtpCredentials({
    host: reqHost,
    port: reqPort,
    secure: reqSecure,
    username: reqUser,
    password: reqPass,
    fromEmail: reqFrom,
    fromName: reqFromName
  });

  const targetRecipient = (recipientEmail && recipientEmail.trim()) || creds.fromEmail || 'events@columbiamarket.org';
  const logs: string[] = [];
  const startTime = Date.now();

  if (!creds.hasRealCredentials) {
    logs.push(`[Notice] Standard mock/empty credentials detected (Host: ${creds.host}).`);
    logs.push(`[1/3] Generating on-demand virtual SMTP test inbox...`);

    try {
      const testAccount = await nodemailer.createTestAccount();
      const testTransporter = nodemailer.createTransport({
        host: 'smtp.ethereal.email',
        port: 587,
        secure: false,
        auth: {
          user: testAccount.user,
          pass: testAccount.pass
        }
      });

      logs.push(`[2/3] Connected to Virtual Gateway (${testAccount.user}) on port 587.`);

      const info = await testTransporter.sendMail({
        from: `"${creds.fromName}" <${creds.fromEmail}>`,
        to: targetRecipient,
        replyTo: creds.replyTo,
        subject: `[SMTP Test] Columbia Community Festival Gateway Verification`,
        text: `This is a test notification generated by Columbia Festival Mailer.\n\nSender: ${creds.fromName} <${creds.fromEmail}>\nRecipient: ${targetRecipient}\nTime: ${new Date().toISOString()}`,
        html: `
          <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; background-color: #f7f5ee; border-radius: 16px; border: 1px solid #e8e2d6;">
            <div style="background-color: #5A5A40; color: #ffffff; padding: 18px 24px; border-radius: 12px; margin-bottom: 20px;">
              <h2 style="margin: 0; font-size: 20px;">✓ SMTP Connection Operational</h2>
              <p style="margin: 4px 0 0 0; font-size: 13px; opacity: 0.9;">Columbia Community Vendor Marketplace</p>
            </div>
            <p style="font-size: 15px; color: #3d3a30; line-height: 1.6;">
              Your test message was successfully dispatched to <strong>${targetRecipient}</strong>.
            </p>
          </div>
        `
      });

      const previewUrl = nodemailer.getTestMessageUrl(info) || undefined;
      const latencyMs = Date.now() - startTime;
      logs.push(`[3/3] Test message successfully delivered to ${targetRecipient}! (Message-ID: ${info.messageId}) [${latencyMs}ms]`);

      return res.status(200).json({
        success: true,
        method: 'virtual',
        messageId: info.messageId,
        previewUrl,
        recipient: targetRecipient,
        latencyMs,
        isTestAccount: true,
        logs
      });
    } catch (etherealErr: any) {
      return res.status(200).json({
        success: false,
        error: etherealErr.message,
        recipient: targetRecipient,
        logs
      });
    }
  }

  logs.push(`[1/4] Establishing TCP socket to ${creds.host}:${creds.port}...`);

  try {
    const transporter = nodemailer.createTransport({
      host: creds.host,
      port: creds.port,
      secure: creds.secure,
      auth: {
        user: creds.username,
        pass: creds.password
      },
      tls: {
        rejectUnauthorized: false
      },
      connectionTimeout: 12000,
      greetingTimeout: 10000,
      socketTimeout: 15000
    });

    await transporter.verify();
    logs.push(`[2/4] SMTP server verified successfully! Authentication accepted.`);

    const fromHeader = creds.fromName ? `"${creds.fromName}" <${creds.fromEmail}>` : creds.fromEmail;
    const info = await transporter.sendMail({
      from: fromHeader,
      to: targetRecipient,
      replyTo: creds.replyTo,
      subject: `[SMTP Verified] Columbia Festival Gateway Connection Test`,
      text: `Live SMTP verification confirmation.\nHost: ${creds.host}\nPort: ${creds.port}\nSender: ${fromHeader}\nRecipient: ${targetRecipient}`,
      html: `
        <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; background-color: #f7f5ee; border-radius: 16px; border: 1px solid #e8e2d6;">
          <div style="background-color: #5A5A40; color: #ffffff; padding: 18px 24px; border-radius: 12px; margin-bottom: 20px;">
            <h2 style="margin: 0; font-size: 20px;">✓ SMTP Connection Operational</h2>
          </div>
          <p style="font-size: 15px; color: #3d3a30;">Live verification message delivered to <strong>${targetRecipient}</strong>.</p>
        </div>
      `
    });

    const latencyMs = Date.now() - startTime;
    logs.push(`[3/3] Delivered to ${targetRecipient} in ${latencyMs}ms (ID: ${info.messageId})`);

    return res.status(200).json({
      success: true,
      method: 'smtp',
      messageId: info.messageId,
      recipient: targetRecipient,
      latencyMs,
      logs
    });
  } catch (error: any) {
    return res.status(200).json({
      success: false,
      error: error.message || 'SMTP Connection failed',
      recipient: targetRecipient,
      logs
    });
  }
}
